/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OtomasyonOdev;

import java.awt.FlowLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Zafer
 */
public class Ekle_GuncelleForm extends javax.swing.JFrame {

    /**
     * Creates new form Ekle_GuncelleForm
     */
    
ResultSet rs;
VeriTabaniIslemleri oto;
public String KullaniciID;
public String SecilenCalisan="";
 int [] CalisanID;
    public Ekle_GuncelleForm() {
     initComponents();
        
        oto=new VeriTabaniIslemleri();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        Calisan_ComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Gorev_TextArea1 = new javax.swing.JTextArea();
        Guncellebt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Baslangic_TextField = new javax.swing.JTextField();
        Bitis_TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Bitiş Tarihi:");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(190, 87));

        Gorev_TextArea1.setColumns(14);
        Gorev_TextArea1.setFont(new java.awt.Font("Wild Words", 0, 10)); // NOI18N
        Gorev_TextArea1.setRows(4);
        Gorev_TextArea1.setPreferredSize(new java.awt.Dimension(158, 85));
        jScrollPane1.setViewportView(Gorev_TextArea1);
        Gorev_TextArea1.getAccessibleContext().setAccessibleParent(this);

        Guncellebt.setLabel("Güncelle");
        Guncellebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuncellebtActionPerformed(evt);
            }
        });

        jLabel3.setText("ÇalışanAdı:");

        jLabel4.setText("Görev:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Güncelleneme");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setText("Başlangıç Tarihi:");

        Baslangic_TextField.setPreferredSize(new java.awt.Dimension(6, 27));

        Bitis_TextField.setMinimumSize(new java.awt.Dimension(6, 27));
        Bitis_TextField.setPreferredSize(new java.awt.Dimension(6, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bitis_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Baslangic_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Guncellebt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Calisan_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calisan_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Baslangic_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Bitis_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guncellebt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuncellebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuncellebtActionPerformed
        // TODO add your handling code here:
        if (Guncellebt.getText().equals("Ekle")) {
               if(oto.GorevEkle(Gorev_TextArea1.getText(),Baslangic_TextField.getText(),Bitis_TextField.getText(),CalisanID[Calisan_ComboBox.getSelectedIndex()],Integer.valueOf(KullaniciID)))
                    JOptionPane.showMessageDialog(this,"Gorev Ekleme Başarılı");
                else
                JOptionPane.showMessageDialog(this,"Gorev Ekleme Başarısız Oldu");
        }
        else{
        String sorgu="Select c.CalisanID from calisan c where c.CalisanAD=? and c.BolumIDFK=(Select BolumIDFK from yonetici where YoneticiID=?)";
        rs=oto.Cekme(sorgu,SecilenCalisan,KullaniciID);
            try {
                rs.next();
                int secilenID=Integer.valueOf(rs.getString("CalisanID"));
                  if(oto.GorevGuncelle(Gorev_TextArea1.getText(),Baslangic_TextField.getText(),Bitis_TextField.getText(),secilenID,Integer.valueOf(KullaniciID)))
                        JOptionPane.showMessageDialog(this,"Gorev Guncelleme Başarılı");
                    else
                        JOptionPane.showMessageDialog(this,"Gorev Guncelleme Başarısız Oldu");      
                
            } catch (SQLException ex) {
                Logger.getLogger(Ekle_GuncelleForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_GuncellebtActionPerformed
    public void calisanGetir() throws SQLException{
        String sorgu="Select c.CalisanID,c.CalisanAD,c.durum from calisan c where c.BolumIDFK=(Select BolumIDFK from yonetici where YoneticiID=?)";
        rs=oto.Cekme(sorgu, KullaniciID);
        rs.last();
        CalisanID = new int[rs.getRow()];
        rs.beforeFirst();
        int i=0;
        while(rs.next()){
        Calisan_ComboBox.addItem(rs.getString("CalisanAd")+" - "+donustur(rs.getString("durum")));
        CalisanID[i]=rs.getInt("CalisanID");
        i++;
        }
       }
    public void secilenCalisan(){
        Calisan_ComboBox.setEnabled(false);
        Calisan_ComboBox.removeAllItems();
        Calisan_ComboBox.addItem(SecilenCalisan);
        
    }
    public void formudegis(boolean a){
        if (a) {
            Guncellebt.setText("Ekle");
            jLabel5.setText("Gorev Ekle");
        }
        else{}
    }
    private String donustur(String a){
        if (a.equals("0")) {
            return "Boşta";
        }
        else
            return "Dolu";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ekle_GuncelleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ekle_GuncelleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ekle_GuncelleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ekle_GuncelleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ekle_GuncelleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Baslangic_TextField;
    public javax.swing.JTextField Bitis_TextField;
    public javax.swing.JComboBox<String> Calisan_ComboBox;
    public javax.swing.JTextArea Gorev_TextArea1;
    private javax.swing.JButton Guncellebt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
