/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OtomasyonOdev;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.TableView;

/**
 *
 * @author Zafer
 */
public class Gorevler extends javax.swing.JFrame {

    /**
     * Creates new form Gorevler
     */
    
ResultSet rs;
VeriTabaniIslemleri oto;
 Ekle_GuncelleForm ge=new Ekle_GuncelleForm();
        
    public Gorevler() {
        initComponents();
             oto=new VeriTabaniIslemleri();//yapılandırıcı fonksiyon veri tabanı bağlantısını kuracak
    //tablodoldur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablo.setAutoCreateRowSorter(true);
        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablo);

        jButton1.setText("Görev Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Seçili Görevi Güncelle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Seçili Görevi Sil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(90, 90, 90)
                .addComponent(jButton3)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       ge.KullaniciID=KullaniciID;
    try {
        ge.formudegis(true);
        ge.calisanGetir();
    } catch (SQLException ex) {
        Logger.getLogger(Gorevler.class.getName()).log(Level.SEVERE, null, ex);
    }
        ge.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     ge.SecilenCalisan=tablo.getValueAt(tablo.getSelectedRow(),1).toString();
            ge.KullaniciID=KullaniciID;

    try {
        ge.calisanGetir();
    } catch (SQLException ex) {
        Logger.getLogger(Gorevler.class.getName()).log(Level.SEVERE, null, ex);
    }
     ge.secilenCalisan();
        ge.Gorev_TextArea1.setText(tablo.getValueAt(tablo.getSelectedRow(),2).toString());
        ge.Baslangic_TextField.setText(tablo.getValueAt(tablo.getSelectedRow(),4).toString());
        ge.Bitis_TextField.setText(tablo.getValueAt(tablo.getSelectedRow(),5).toString());
        ge.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here
        String a=tablo.getValueAt(tablo.getSelectedRow(),1).toString();
        rs=oto.Cekme("SELECT CalisanID FROM calisan where CalisanAD=?",a);
    try {
        rs.next();
        oto.GorevSilme(rs.getString("CalisanID"), KullaniciID);
        tablodoldur();
        JOptionPane.showMessageDialog(this,"Başarıyla Silindi");
    } catch (SQLException ex) {
        Logger.getLogger(Gorevler.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton3ActionPerformed
    public String KullaniciID;  
    public  void tablodoldur()
        {
            int sonsatir=0;
            int satirlar=0;
            String sorgu="Select y.yoneticiAD,c.CalisanAD,g.Gorev,g.GorevBaslangicTarihi,g.GorevBitisTarihi,b.BolumADI from bolum b, gorev g,calisan c,yonetici y "
                    + "where g.YoneticiIDFK=y.YoneticiID and g.CalisanIDFK=c.CalisanID and c.BolumIDFK=b.BolumID and y.BolumIDFK=b.BolumID and "
                    + "b.BolumID=(Select BolumIDFK from yonetici where YoneticiID='"+KullaniciID+"')";
    try {
       rs=oto.Cekme(sorgu);
        if (rs.next()) {
            rs.last();
            sonsatir=rs.getRow();
            rs.beforeFirst();
        }
         String veriler[][]= new String[sonsatir][6];
        while(rs.next())
        {
        veriler[satirlar][0]=rs.getString("yoneticiAD");
        veriler[satirlar][1]=rs.getString("CalisanAD");
        veriler[satirlar][2]=rs.getString("Gorev");
        veriler[satirlar][3]=rs.getString("BolumADI");       
        veriler[satirlar][4]=rs.getString("GorevBaslangicTarihi");       
        veriler[satirlar][5]=rs.getString("GorevBitisTarihi");
        satirlar++;
        }
        String baslik[]={"yoneticiAD","CalisanAD ","Gorev","BolumADI","GorevBaslangicTarihi","GorevBitisTarihi"};
        DefaultTableModel tablomodeli=new DefaultTableModel(veriler,baslik);
        tablo.setModel(tablomodeli);
    } catch (SQLException ex) {
        Logger.getLogger(Yonetici.class.getName()).log(Level.SEVERE, null, ex);
    }         
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gorevler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gorevler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gorevler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gorevler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gorevler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablo;
    // End of variables declaration//GEN-END:variables
}
