/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OtomasyonOdev;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Zafer
 */
public class KullaniciGiris extends javax.swing.JFrame {

    ResultSet rs;
    VeriTabaniIslemleri oto;
    /**
     * Creates new form KayitEkle
     */
    public KullaniciGiris() {
        initComponents();
        oto=new VeriTabaniIslemleri();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KadTF = new javax.swing.JTextField();
        GirisBt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SifreTF = new javax.swing.JPasswordField();
        Gorevli_RadioButton = new javax.swing.JRadioButton();
        Yonetici_RadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GirisBt.setText("Giriş");
        GirisBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirisBtActionPerformed(evt);
            }
        });

        jLabel1.setText("Kullancı Adı:");

        jLabel2.setText("Şifre:");

        Gorevli_RadioButton.setText("Görevli");
        Gorevli_RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gorevli_RadioButtonActionPerformed(evt);
            }
        });

        Yonetici_RadioButton.setText("Yönetici");
        Yonetici_RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Yonetici_RadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Yonetici_RadioButton)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SifreTF, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Gorevli_RadioButton))
                    .addComponent(KadTF))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(GirisBt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SifreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gorevli_RadioButton)
                    .addComponent(Yonetici_RadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(GirisBt)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void kullaniciKontrol(String sorgu,boolean tip){

        try {
           rs=oto.Cekme(sorgu,KadTF.getText());
           
            if (!rs.next()) {
                
            JOptionPane.showMessageDialog(this,"Kullanıcı adi yanlış");
            }
            else {
                if (rs.getString("sifre").equals(SifreTF.getText())) {
                  
                    Gorevler gorev=new Gorevler();
                    if (tip) {
                        gorev.jButton1.setVisible(true);
                        gorev.jButton2.setVisible(true);
                        gorev.jButton3.setVisible(true);
                    }
                    else{
                       gorev.jButton1.setVisible(false);
                        gorev.jButton2.setVisible(false);
                        gorev.jButton3.setVisible(false);
                    }
                    gorev.setVisible(true);
                    gorev.KullaniciID=rs.getString("KullaniciID");
                    gorev.tablodoldur();
                    this.setVisible(false);
                } else {
                    //sifre yanlıs
                    JOptionPane.showMessageDialog(this,"Sifre Yanlış");
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Kullanıcı adi yanlış");
            //ad yanlıs
        }
    }
    private void GirisBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirisBtActionPerformed
        String sorgu;
        if (Yonetici_RadioButton.isSelected()) {
            sorgu = "Select YoneticiID as KullaniciID, YoneticiSifre as sifre from yonetici where YoneticiID=(select YoneticiID from yonetici where YoneticiAD=?)";
            kullaniciKontrol(sorgu,true);
        }
        else if(Gorevli_RadioButton.isSelected())
        {
        sorgu = "Select CalisanID as KullaniciID, calisanSIFRE as sifre from calisan where CalisanID=(select CalisanID from calisan where CalisanAD=?)";
            kullaniciKontrol(sorgu,false);
        }
        else{
            JOptionPane.showMessageDialog(this, "Lütfen yoneticimi görevlimi olduğunuzu seçiniz");
        }

    }//GEN-LAST:event_GirisBtActionPerformed

    private void Gorevli_RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gorevli_RadioButtonActionPerformed
         
        if (Gorevli_RadioButton.isSelected()) {
            Yonetici_RadioButton.setSelected(false);
        }
    }//GEN-LAST:event_Gorevli_RadioButtonActionPerformed

    private void Yonetici_RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Yonetici_RadioButtonActionPerformed
        if (Yonetici_RadioButton.isSelected()) {
            Gorevli_RadioButton.setSelected(false);
        }
    }//GEN-LAST:event_Yonetici_RadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new KullaniciGiris().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GirisBt;
    private javax.swing.JRadioButton Gorevli_RadioButton;
    private javax.swing.JTextField KadTF;
    private javax.swing.JPasswordField SifreTF;
    private javax.swing.JRadioButton Yonetici_RadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
